
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/consultation/espacerecherchemed.css');?>

<?php
echo $this->headLink()->appendStylesheet($this->basePath().'/js/plugins/jPlayer-2.9.2/dist/skin/blue.monday/css/jplayer.blue.monday.min.css');

echo $this->headScript()->appendFile($this->basePath().'/js/plugins/jPlayer-2.9.2/dist/jplayer/jquery.jplayer.min.js');
echo $this->headScript()->appendFile($this->basePath().'/js/plugins/jPlayer-2.9.2/dist/add-on/jplayer.playlist.min.js');
?>

<script>
//POUR LE MENU GAUCHE dans -elementgauche.phtml
$('#plus_deces').toggle(true);
$("#deces").replaceWith("<li id='deces' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='<?php echo $this->basePath().'/images_icons/moins-vert.PNG'?>' alt='Liste' /> Consultations </span></a></li>");
dep_deces1();
$('#liste_recherche_style').css({'font-weight':'bold','color':'white','font-size':'22px'});
</script>

<style>
#contenu{ visibility: hidden }
.jp-playlist span{ 
 	float:right;
} 

         .jp-ajouter{
              position:relative;
              width:19px;
              height:19px;
              background:url(<?php echo $this->basePath()."/js/plugins/jPlayer-2.9.2/dist/skin/blue.monday/image/jplayer.blue.monday.jpg"?>) -120px -271px no-repeat; margin-left:5px
              display: inline;border:transparent; margin-bottom: 5px;
         	  right:-60px;
              top:0;
         }
             .jp-ajouter input{
         	  width:19px; height: 49px;
         	  position:absolute;
              opacity:1;
              -moz-opacity:0;
              filter:alpha(opacity=0);
              right:0px; 
              top:-30px; cursor:pointer; 
         }
</style>

<script>
$(window).load(function () {

	$('#wait').toggle(false);
	$('#contenu').fadeIn().css({'visibility':'visible'});
	 
});

</script>


<div id="titre" style='font-family: police2; text-decoration:none; color: green; font-size: 20px; font-weight: bold; padding-left:20px;'> <i style='font-size: 25px;'>&curren;</i> LISTE DES CONSULTATIONS</div>
<div id="contenu" style='min-height: 200px;'>
<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>

<div id="AfficherLecteur" style='margin: 40px;'>
<!-- *************** --> 
</div>


</div>



<script type="text/javascript">
var base_url = window.location.toString();
var tabUrl = base_url.split("public");

function AppelLecteurMp3(){
 var chemin = tabUrl[0]+'public/consultation/afficher-mp3';
 $.ajax({
 	url: chemin ,
    type: 'POST',
    data: 'id='+1,
    success: function (response) {
     	var result = jQuery.parseJSON(response); 
     	$('#AfficherLecteur').html(result);
    },
    error:function(e){console.log(e);alert("Une erreur interne est survenue!");},
    dataType: "html"
 
 });
}
AppelLecteurMp3();


function scriptAjoutMp3(){
$(function () {
    $('#my_form').change(function (e) {
        // On empêche le navigateur de soumettre le formulaire
        e.preventDefault();
        
        var $form = $(this);
        var formdata = (window.FormData) ? new FormData($form[0]) : null;
        var data = (formdata !== null) ? formdata : $form.serialize();
        
        var chemin = tabUrl[0]+'public/consultation/ajouter-mp3';
        $.ajax({
            //url: $form.attr('action'),
        	url: chemin ,
            type: $form.attr('method'),
            contentType: false, // obligatoire pour de l'upload
            processData: false, // obligatoire pour de l'upload
            data: data,
            success: function (response) {
                // La réponse du serveur
            	var result = jQuery.parseJSON(response); //alert(result); exit();
            	
            	$('#AfficherLecteur').empty(); 
            	$('#AfficherLecteur').html(result);
            }
        });
	});
});
}


</script>
