
<ul>
	<!-- MENU ***SURVEILLANT DE SERVICE*** -->
	<li id="naissance"><a href="">
	    <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:18px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/add.PNG'?>' alt='Liste' /> Surveillant de service </span></a> </li>

	<li id="plus_naissance" style="background: #4a5765;" >
	   <div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->url('consultation', array('action'=> 'recherche'));?>"  >
	       <span id="ajouter_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>' alt='Liste' /> Consultations</span></a>
	   </div>
	   <div id="liste_naiss"style="margin-left:30px; height:40px;"><a href="<?php echo $this->url('consultation', array('action'=> 'espace-recherche-surv'));?>">
	       <img style="margin-left:5px; display: inline;" src='<?php echo $this->basePath().'/images_icons/Search_22.PNG'?>' alt='Liste' />
	       <span id="liste_style" style="font-size:15px; color: white; font-family:Times New Roman;">Recherche</span></a>
	   </div>
	</li>

	<!-- MENU ***MEDECIN DE SERVICE*** -->
	<li id="deces"><a href="">
	    <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:18px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/add.PNG'?>' alt='Liste' /> M&eacute;decin de service </span></a> </li>

	<li id="plus_deces" style="background: #4a5765;" >

	   <div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->url('consultation', array('action'=> 'consultation-medecin'));?>"  >
	       <span id="declarer_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/dossier.PNG'?>' alt='Liste' /> Consultations</span></a>
	   </div>

	   <div style="margin-left:30px; height:40px;"><a href="<?php echo $this->url('consultation', array('action'=> 'espace-recherche-med'));?>">
	       <img style="margin-left:5px; display: inline;" src='<?php echo $this->basePath().'/images_icons/Search_22.PNG'?>' alt='Liste' />
	       <span id="liste_deces_style" style="font-size:15px; color: white; font-family:Times New Roman;">Recherche</span></a>
	   </div>
	</li>

</ul>

<?php
//CHOISIR LE MENU A AFFICHER SELON QUE C'EST LE MEDECIN OU SUR LE SURVEILLANT
// $identity = (array) Zend_Auth::getInstance()->getIdentity();
// $type = $identity['TYPE'];

// if($type == 'SURVEILLANT'){ ?>
<!-- <script> -->
// $("#deces").toggle(false);
<!-- </script> -->
// <?php
// }
// else if($type == 'MEDECIN'){ ?>
<!-- <script> -->
// $("#naissance").toggle(false);
<!-- </script> -->
// <?php
//      }
?>

<script>
//NAISSANCE
function dep1(){
	$('#naissance').click(function(){
		$("#naissance").replaceWith("<li id='naissance'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:18px; font-family:Times New Roman;'> <img style='display: inline;' src='"+<?php echo $this->basePath().'/images_icons/add.PNG';?>+"' alt='Liste' /> Surveillant de service </span></a></li>");
		dep2();
	    $('#plus_naissance').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep2(){
	$('#naissance').click(function(){
		$("#naissance").replaceWith("<li id='naissance' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:18px; font-family:Times New Roman;'> <img style='display: inline;' src='"+<?php echo $this->basePath().'/images_icons/moins-vert.PNG';?>+"' alt='Liste' /> Surveillant de service </span></a></li>");
		dep1();
	    $('#plus_naissance').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_naissance').toggle(false);
$('#naissance').click(function(){
	$("#naissance").replaceWith("<li id='naissance' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:18px; font-family:Times New Roman;'> <img style='display: inline;' src='"+<?php echo $this->basePath().'/images_icons/moins-vert.PNG';?>+"' alt='Liste' /> Surveillant de service </span></a></li>");
	dep1();
    $('#plus_naissance').animate({
        height : 'toggle'
    },1000);
 return false;
});

//*******************************************************************************************************************************
//MEDECIN DE SERVICE
function dep_deces1(){
	$('#deces').click(function(){
		$("#deces").replaceWith("<li id='deces'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:18px; font-family:Times New Roman;'> <img style='display: inline;' src='"+<?php echo $this->basePath().'/images_icons/add.PNG';?>+"' alt='Liste' /> M&eacute;decin de service </span></a></li>");
		dep_deces2();
	    $('#plus_deces').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_deces2(){
	$('#deces').click(function(){
		$("#deces").replaceWith("<li id='deces' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:18px; font-family:Times New Roman;'> <img style='display: inline;' src='"+<?php echo $this->basePath().'/images_icons/moins-vert.PNG';?>+"' alt='Liste' /> M&eacute;decin de service </span></a></li>");
		dep_deces1();
	    $('#plus_deces').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_deces').toggle(false);
$('#deces').click(function(){
	$("#deces").replaceWith("<li id='deces' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:18px; font-family:Times New Roman;'> <img style='display: inline;' src='"+<?php echo $this->basePath().'/images_icons/moins-vert.PNG';?>+"' alt='Liste' /> M&eacute;decin de service </span></a></li>");
	dep_deces1();
$('#plus_deces').animate({
    height : 'toggle'
},1000);
return false;
});

</script>