<style>
</style>
<ul>
	<!-- MENU ***HOSPITALISATION*** -->
	<li id="dossier_personnel"><a href="">
	    <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:18px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/add.PNG'?>' alt='Liste' /> Hospitalisation </span></a> </li>

	<li id="plus_dossier_personnel" style="background: #4a5765;" >

	   <div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->basePath().'/hospitalisation/liste';?>"  >
	       <span id="nouveau_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;">
	       <img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.png'?>' alt='Liste' /> Liste</span></a>
	   </div>

	   <div style="margin-left:30px; height:40px;"><a href="<?php echo $this->basePath().'/hospitalisation/suivi-patient';?>">
	       <img style="margin-left:5px; display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.png'?>' alt='Liste' />
	       <span id="suivi_patient_style" style="font-size:15px; color: white; font-family:Times New Roman;">Suivi des patients</span></a>
	   </div>
	   
	   <?php //Utiliser dans l'interface du medecin ?>
	   <div id="en_cours_icone" style="margin-left:30px; height:40px;"><a href="<?php echo $this->basePath().'/hospitalisation/en-cours';?>">
	       <img style="margin-left:5px; display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.png'?>' alt='Liste' />
	       <span id="en_cours_style" style="font-size:15px; color: white; font-family:Times New Roman;">En cours (M&eacute;decin)</span></a>
	   </div>
	   <?php ?>
	</li>




	<!-- MENU ***EXAMENS** -->
	<li id="operation"><a href="">
	    <span style="margin-left:0px; color: #48ce77; font-weight:bold; font-size:18px; font-family:Times New Roman;"> <img id="image" style="display: inline;" src='<?php echo $this->basePath().'/images_icons/add.png'?>' /> Demandes d'examen </span></a> </li>

	<li id="plus_operation" style="background: #4a5765;" >
	   <!-- PARTIE DES TRANSFERTS -->
	   <div style="margin-left:30px; height:40px; padding-top:20px;"><a href="<?php echo $this->url('hospitalisation', array('action'=> 'liste-demandes-examens'));?>"  >
	       <span id="recherche_style" style="margin-left:5px; color: white; font-size:15px; font-family:Times New Roman;"><img style="display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.png'?>' /> En cours </span></a>
	   </div>
	   
	   <div id="liste_recherche"style="margin-left:30px; height:40px;"><a href="<?php echo $this->basePath().'/hospitalisation/liste-examens-effectues';?>">
	       <img style="margin-left:5px; display: inline;" src='<?php echo $this->basePath().'/images_icons/liste.png'?>' alt='Liste' />
	       <span id="liste_style" style="font-size:15px; color: white; font-family:Times New Roman;">Recherche</span></a>
	   </div>
	</li>

</ul>

<?php
//CHOISIR LE MENU A AFFICHER SELON QUE C'EST LE MEDECIN OU SUR LE SURVEILLANT
$user = $this->layout()->user;
$role = $user->role;

if($role == 'infirmier'){ ?>
<script>
$("#operation").toggle(false);
$("#liste_recherche").toggle(false);
</script>
<?php
}
else if($role == 'laborantin'){ ?>
<script>
$("#dossier_personnel").toggle(false);
</script>
<?php
     }
?>


<script>
$("#en_cours_icone").toggle(false);
//*******************************************************************************************************************************
//operation
function dep1(){
	$('#operation').click(function(){
		$("#operation").replaceWith("<li id='operation'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:18px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/add.PNG' alt='Liste' /> Demandes d'examen </span></a></li>");
		dep2();
	    $('#plus_operation').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep2(){
	$('#operation').click(function(){
		$("#operation").replaceWith("<li id='operation' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:18px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moins-vert.PNG' alt='Liste' /> Demandes d'examen </span></a></li>");
		dep1();
	    $('#plus_operation').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_operation').toggle(false);
$('#operation').click(function(){
	$("#operation").replaceWith("<li id='operation' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:18px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens/public/images_icons/moins-vert.PNG' alt='Liste' /> Demandes d'examen </span></a></li>");
	dep1();
    $('#plus_operation').animate({
        height : 'toggle'
    },1000);
 return false;
});

//*******************************************************************************************************************************
//DECES
function dep_deces1(){
	$('#deces').click(function(){
		$("#deces").replaceWith("<li id='deces'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:18px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens_derniereversion/public/images_icons/add.PNG' alt='Liste' /> D&eacute;c&egrave;s </span></a></li>");
		dep_deces2();
	    $('#plus_deces').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_deces2(){
	$('#deces').click(function(){
		$("#deces").replaceWith("<li id='deces' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:18px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens_derniereversion/public/images_icons/moins-vert.PNG' alt='Liste' /> D&eacute;c&egrave;s </span></a></li>");
		dep_deces1();
	    $('#plus_deces').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_deces').toggle(false);
$('#deces').click(function(){
	$("#deces").replaceWith("<li id='deces' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:18px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens_derniereversion/public/images_icons/moins-vert.PNG' alt='Liste' /> D&eacute;c&egrave;s </span></a></li>");
	dep_deces1();
    $('#plus_deces').animate({
        height : 'toggle'
    },1000);
 return false;
});


//*******************************************************************************************************************************
//ADMISSION
function dep_admission1(){
	$('#admission').click(function(){
		$("#admission").replaceWith("<li id='admission'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:18px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens_derniereversion/public/images_icons/add.PNG' alt='Liste' /> Facturation </span></a></li>");
		dep_admission2();
	    $('#plus_admission').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_admission2(){
	$('#admission').click(function(){
		$("#admission").replaceWith("<li id='admission' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:18px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens_derniereversion/public/images_icons/moins-vert.PNG' alt='Liste' /> Facturation </span></a></li>");
		dep_admission1();
	    $('#plus_admission').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_admission').toggle(false);
$('#admission').click(function(){
	$("#admission").replaceWith("<li id='admission' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:18px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens_derniereversion/public/images_icons/moins-vert.PNG' alt='Liste' /> Facturation </span></a></li>");
	dep_admission1();
$('#plus_admission').animate({
    height : 'toggle'
},1000);
return false;
});


//*******************************************************************************************************************************
//DOSSIER PERSONNEL
function dep_dossier_personnel1(){
	$('#dossier_personnel').click(function(){
		$("#dossier_personnel").replaceWith("<li id='dossier_personnel'><a href=''><span style='margin-left:0px; color: #48ce77; font-weight:bold; font-size:18px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens_derniereversion/public/images_icons/add.PNG' alt='Liste' /> Hospitalisation </span></a></li>");
		dep_dossier_personnel2();
	    $('#plus_dossier_personnel').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

function dep_dossier_personnel2(){
	$('#dossier_personnel').click(function(){
		$("#dossier_personnel").replaceWith("<li id='dossier_personnel' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:18px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens_derniereversion/public/images_icons/moins-vert.PNG' alt='Liste' /> Hospitalisation </span></a></li>");
		dep_dossier_personnel1();
	    $('#plus_dossier_personnel').animate({
	        height : 'toggle'
	    },1000);
	 return false;
	});
}

$('#plus_dossier_personnel').toggle(false);
$('#dossier_personnel').click(function(){
	$("#dossier_personnel").replaceWith("<li id='dossier_personnel' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:18px; font-family:Times New Roman;'> <img style='display: inline;' src='/simens_derniereversion/public/images_icons/moins-vert.PNG' alt='Liste' /> Hospitalisation </span></a></li>");
	dep_dossier_personnel1();
$('#plus_dossier_personnel').animate({
height : 'toggle'
},1000);
return false;
});

</script>