<html>
<?php echo $this->doctype("XHTML1_TRANSITIONAL"), PHP_EOL; ?>
<head>
 <meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,800' rel='stylesheet' type='text/css' />
		
<?php 	
  echo $this->headLink()->prependStylesheet($this->basePath().'/css/bootstrap.min.css');
  echo $this->headLink()->prependStylesheet($this->basePath().'/css/uniform.css');
  echo $this->headLink()->prependStylesheet($this->basePath().'/css/select2.css');
  echo $this->headLink()->prependStylesheet($this->basePath().'/css/jquery.contextMenu.css');
  echo $this->headLink()->prependStylesheet($this->basePath().'/css/matrix-style.css');
  echo $this->headLink()->prependStylesheet($this->basePath().'/css/matrix-media.css');
  echo $this->headLink()->prependStylesheet($this->basePath().'/font-awesome/css/font-awesome.css');
  echo $this->headLink()->prependStylesheet($this->basePath().'/css/tooltipster.css');
  echo $this->headLink()->prependStylesheet($this->basePath().'/css/smoothness/jquery-ui.css');

  $this->headScript()->appendFile($this->basePath().'/js/jquery.min.js');
  $this->headScript()->appendFile($this->basePath().'/js/jquery.tooltipster.min.js');
  $this->headScript()->appendFile($this->basePath().'/js/bootstrap.min.js');
  $this->headScript()->appendFile($this->basePath().'/js/jquery.uniform.js');
  $this->headScript()->appendFile($this->basePath().'/js/select2.min.js');
  $this->headScript()->appendFile($this->basePath().'/js/jquery.dataTables.min.js');
  $this->headScript()->appendFile($this->basePath().'/js/jquery-ui.js');
  
  $this->headScript()->appendFile($this->basePath().'/js/jquery.maskedinput.js');
  $this->headScript()->appendFile($this->basePath().'/js/controle_saisie/controle_saisie.js');?>
  <?php echo $this->headScript();?>
</head>


<body id = "bodbod">
<!--Header-part-->
<div id="header">
  <h1><a href="">Simens admin panel</a></h1>
</div>
<!--close-Header-part-->
<!--top Menu au dessus -->
<div id="user-nav" class="navbar navbar-inverse">
  <ul class="nav">
    <li  class="dropdown" id="profile-messages" ><a title="" href="#"  class="dropdown-toggle">
    <i class="icon icon-user"></i>  <span class="text">Bienvenue utilisateur</span><b class="caret"></b></a>
    </li>

    <li class=""><a title="" href="<?php echo $this->url('login/process', array('action'=>'logout'));?>">
    <i class="icon icon-share-alt"></i> <span class="text">D&eacute;connexion</span></a>
    </li>
  </ul>
</div>
<!--Menu de droite-->
<div id="sidebar">
  <?php echo $this->partial('layout/menugauche-personnel'); ?>
</div>
<div id="content">
  	<div id="content-header">
    <div style="width: 96%; margin-left:25px; ">
    	<hr>
   		 <div class="row-fluid">
	         <?php echo $this->content; ?>
         </div>
  	</div>
	</div>
</div>
<!--Pied de Page debut-->
<div class="row-fluid">
	 <div id="footer" class="span12"><?php echo $this->partial('layout/piedpage-personnel'); ?> </div>
</div>
<!--Fin de pied de page-->
</body>
</html>