
    <?php echo $this->headLink()->prependStylesheet($this->basePath().'/css/matrix-login.css');?>
    <?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/monstyle.css');?>
<!-- MES JS -->
<?php echo $this->headScript()->appendFile($this->basePath().'/js/admin/jsAjax.js');?>

<div class="control-group normal_text">
	<h3>
		<img
			src="<?php echo  $this->basePath()."/images_medecine/logo_extra.png";?>"
			alt="logo"
			style="width: 200px; height: 200px; border: transparent; display: inline;" />
	</h3>
</div>
<div class="control-group">
	<div class="controls">
		<div class="main_input_box">
			<span class="add-on bg_lg"><i class="icon-user"></i></span><span
				style="border-bottom-color: #ffaaee;"><?php echo $this->formRow($form->get('username'));?></span>
		</div>
	</div>
</div>
<div class="control-group">
	<div class="controls">
		<div class="main_input_box">
			<span class="add-on bg_ly"><i class="icon-lock"></i></span><?php echo $this->formRow($form->get('password'));?>
			</div>
	</div>
</div>
<div class="form-actions">
	<!-- 		<span class="pull-left"><a href="#" class="flip-link btn btn-info" id="to-recover">Remember Me ?</a></span> -->
	<span class="pull-left"><?php echo $this->formRow($form->get('rememberme'));?><a
		href="#" class="flip-link btn btn-info" id="to-recover">Remember Me ?</a></span>
	<span class="pull-right"><?php echo $this->formSubmit($form->get('submit'));?></span>
</div>

<div id='info' style='color: black;'></div>

<script>
action();
</script>