<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/matrix-login.css');?>
<?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/monstyle.css');?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'login/process',
    array(
        'action'     => 'authenticate',
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();

if ($this->messages){
    echo '<ul>';
    foreach($this->messages as $message)
    {
        echo '<li>'.$message.'</li>';
    }
    echo '</ul>';
}
?>